### PR TITLE
Added the `serve` task to gulp.

### PR DESCRIPTION
**Pull request by nedp**
It:

1. Runs the `compile` task
2. Runs the server (`app.js`)
3. Watches for the same changes as the `watch` task,
   triggering recompilation and a server restart.

### CODE REVIEW

**Comment by rongduan-zhu** [comment]
Forgot to do ```--save```?  package.json is not updated

**Comment by nedp** [comment]
You're right. Didn't know there was a `--save` option also, thanks.

**Comment by nedp** [comment]
Force pushed ammendment. Repull if needed.

**Comment by nedp** [comment]
Blocked by bug. Closing the PR for now.

**Pull request closed without merging**
