### PR TITLE
added simple test template

### PR DESCRIPTION
**Pull request by rongduan-zhu**
edit:
@neroma/owners 
1. please first install all necessary modules by doing ```npm install``` (you may need to add ```sudo```)
2. install karma-cli by doing ```npm install -g karma-cli```
3. to test, you can either do ```karma start``` or ```gulp test```. I recommend doing ```gulp test``` as it also compiles all necessary files.

### CODE REVIEW

**Comment by nedp** [comment]
`$ npm test` does nothing

**Comment by rongduan-zhu** [comment]
You must first do ```npm install```
To run test, first do ```npm install -g karma-cli```, which installs karma globally. Then to run test, do ```karma start```.

**Comment by rongduan-zhu** [comment]
I'll add readme after #8  is merged. Also add npm script to run test.

**Comment by nedp** [comment]
Can this be merged so https://github.com/neroma/neroma-chat/pull/6 can be tested then merged, so #8 can be merged?

**Comment by rongduan-zhu** [comment]
I'm waiting for someone to approve this before merging.

**Comment by nedp** [comment]
:+1:

**Pull request merged**
