### PR TITLE
added template engine

### PR DESCRIPTION
**Pull request by rongduan-zhu**
@neroma/owners 

Added template engine into express. Now you can choose either to use local copies of libraries or cdn version by specifying the ```USE_LOCAL``` environment variable. If you want to use local copies, add a ```USE_LOCAL``` env variable and assign it a value of 1

### CODE REVIEW

**Comment by nedp** [comment]
environment variables are the sort of thing that work well in readmes

**Comment by rongduan-zhu** [comment]
@nedp Added readme as per request

**Comment by nedp** [comment]
I LOVE IT

**Comment by nedp** [comment]
All good as far as I can tell

**Comment by rongduan-zhu** [comment]
waiting for #6 to be merged

**Comment by nedp** [comment]
:+1:

**Comment by Druddigon** [comment]
Don't like using handlebars to do this because it has the same syntax as angular ```{{ ... }}```.

**Comment by nedp** [comment]
I agree, it's clunky. What's a better alternative though?

**Comment by rongduan-zhu** [comment]
Well, an alternative that can be done using the current template engine is 
```handlebars
{{{{raw-helper}}}}
things that template engine won't render
{{{{/raw-helper}}}}
```
Reference [here](http://handlebarsjs.com/block_helpers.html#raw-blocks)

The alternative would be Express's default template engine, [Jade](http://jade-lang.com/). Which I don't really like because it's kinda like coffeescript for HTML. There is a way to write proper HTML in Jade which you add a ```.```. And iirc everything after the ```.``` can be normal html.

**Comment by nedp** [comment]
Seems worse than handlebars for us.

**Comment by rongduan-zhu** [comment]
Yes, I agree. So I prefer handlebars. As it is more of the more popular template engines for Nodejs

**Pull request merged**
